 // This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "common": {
    "Login": "Login",
    "Registration": "Registration"
  }
}

export default Resources;
