import { AssetType, CurrencyCode, NumberString } from '@packages/types';

export enum MoexColumnsVariants {
  SECID = 'SECID',
  BOARDID = 'BOARDID',
  BID = 'BID',
  BIDDEPTH = 'BIDDEPTH',
  OFFER = 'OFFER',
  OFFERDEPTH = 'OFFERDEPTH',
  SPREAD = 'SPREAD',
  BIDDEPTHT = 'BIDDEPTHT',
  OFFERDEPTHT = 'OFFERDEPTHT',
  OPEN = 'OPEN',
  LOW = 'LOW',
  HIGH = 'HIGH',
  LAST = 'LAST',
  LASTCHANGE = 'LASTCHANGE',
  LASTCHANGEPRCNT = 'LASTCHANGEPRCNT',
  QTY = 'QTY',
  VALUE = 'VALUE',
  VALUE_USD = 'VALUE_USD',
  WAPRICE = 'WAPRICE',
  LASTCNGTOLASTWAPRICE = 'LASTCNGTOLASTWAPRICE',
  WAPTOPREVWAPRICEPRCNT = 'WAPTOPREVWAPRICEPRCNT',
  WAPTOPREVWAPRICE = 'WAPTOPREVWAPRICE',
  CLOSEPRICE = 'CLOSEPRICE',
  MARKETPRICETODAY = 'MARKETPRICETODAY',
  MARKETPRICE = 'MARKETPRICE',
  LASTTOPREVPRICE = 'LASTTOPREVPRICE',
  NUMTRADES = 'NUMTRADES',
  VOLTODAY = 'VOLTODAY',
  VALTODAY = 'VALTODAY',
  VALTODAY_USD = 'VALTODAY_USD',
  ETFSETTLEPRICE = 'ETFSETTLEPRICE',
  TRADINGSTATUS = 'TRADINGSTATUS',
  UPDATETIME = 'UPDATETIME',
  LASTBID = 'LASTBID',
  LASTOFFER = 'LASTOFFER',
  LCLOSEPRICE = 'LCLOSEPRICE',
  LCURRENTPRICE = 'LCURRENTPRICE',
  MARKETPRICE2 = 'MARKETPRICE2',
  NUMBIDS = 'NUMBIDS',
  NUMOFFERS = 'NUMOFFERS',
  CHANGE = 'CHANGE',
  TIME = 'TIME',
  HIGHBID = 'HIGHBID',
  LOWOFFER = 'LOWOFFER',
  PRICEMINUSPREVWAPRICE = 'PRICEMINUSPREVWAPRICE',
  OPENPERIODPRICE = 'OPENPERIODPRICE',
  SEQNUM = 'SEQNUM',
  SYSTIME = 'SYSTIME',
  CLOSINGAUCTIONPRICE = 'CLOSINGAUCTIONPRICE',
  CLOSINGAUCTIONVOLUME = 'CLOSINGAUCTIONVOLUME',
  ISSUECAPITALIZATION = 'ISSUECAPITALIZATION',
  ISSUECAPITALIZATION_UPDATETIME = 'ISSUECAPITALIZATION_UPDATETIME',
  ETFSETTLECURRENCY = 'ETFSETTLECURRENCY',
  VALTODAY_RUR = 'VALTODAY_RUR',
  TRADINGSESSION = 'TRADINGSESSION',
  TRENDISSUECAPITALIZATION = 'TRENDISSUECAPITALIZATION',
}

export enum MoexHistoryColumns {
  BOARDID = 'BOARDID',
  TRADEDATE = 'TRADEDATE',
  SHORTNAME = 'SHORTNAME',
  SECID = 'SECID',
  NUMTRADES = 'NUMTRADES',
  VALUE = 'VALUE',
  OPEN = 'OPEN',
  LOW = 'LOW',
  HIGH = 'HIGH',
  LEGALCLOSEPRICE = 'LEGALCLOSEPRICE',
  WAPRICE = 'WAPRICE',
  CLOSE = 'CLOSE',
  VOLUME = 'VOLUME',
  MARKETPRICE2 = 'MARKETPRICE2',
  MARKETPRICE3 = 'MARKETPRICE3',
  ADMITTEDQUOTE = 'ADMITTEDQUOTE',
  MP2VALTRD = 'MP2VALTRD',
  MARKETPRICE3TRADESVALUE = 'MARKETPRICE3TRADESVALUE',
  ADMITTEDVALUE = 'ADMITTEDVALUE',
  WAVAL = 'WAVAL',
  TRADINGSESSION = 'TRADINGSESSION',
}

export type MoexColumnValue = string | number | null;

export type MoexMarketData = {
  marketdata: {
    columns: MoexColumnsVariants[];
    data: MoexColumnValue[][];
  };
};

export type MoexHistoryData = {
  history: {
    columns: MoexHistoryColumns[];
    data: MoexColumnValue[][];
  };
};

export type MoexAssetHistoryPrice = {
  symbol: string;
  date: Date;
  open: NumberString;
  high: NumberString;
  low: NumberString;
  close: NumberString;
  volume: NumberString;
  currencyCode: CurrencyCode;
  type: AssetType;
};
